name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker build . --file Dockerfile --tag aideryusupov/docker:latest 
        docker run aideryusupov/docker:latest 
        docker login -u aideryusupov -p razvedka1rota
        docker push aideryusupov/docker:latest 
        
  trivy:
     runs-on: ubuntu-22.04
     steps:
       - name: scanning
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: 'aideryusupov/docker:latest'
           format: 'table'
           exit-code: '1'
           ignore-unfixed: true
           vuln-type: 'os,library'
           severity: 'CRITICAL,HIGH'
           
